import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
      <body>
        <header className="border-b">
          <div className="mx-auto max-w-7xl px-4 py-2">
            <Navbar />
          </div>
        </header>

        <main className="mx-auto max-w-7xl px-4 py-6">
          {children}
        </main>
      </body>
		</html>
	);
}
